name: test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    - name: initialize conda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: dropsonde_test
        auto-activate-base: false
        use-mamba: true
        miniforge-variant: Mambaforge
        miniforge-version: latest
    - name: install conda environment
      run:
        mamba env update -n dropsonde_test -f environment.yaml
    - name: run pydropsonde 
      run: pydropsonde -c ./orcestra_drop.cfg
           
     
